import matplotlib.pyplot as plt
import pandas as pd


def plot_benchmark_results(csv_file):
    # Load the CSV data
    data = pd.read_csv(csv_file)

    # Extract input sizes
    input_sizes = data["Input Size"]

    # Prepare the figure
    plt.figure(figsize=(10, 6))

    # Iterate through each column (skipping the first column for "Input Size")
    for column in data.columns[1:]:
        algorithm_name = column.title()  # Extract algorithm name
        plt.plot(input_sizes, data[column], label=algorithm_name)

    # Configure the plot
    plt.xscale("log")  # Set x-axis to logarithmic scale
    plt.yscale("log")  # Set y-axis to logarithmic scale
    plt.xlabel("Input Size (log scale)")
    plt.ylabel("Runtime (microseconds)")
    plt.title("Benchmark Results: Sorting Algorithms")
    plt.legend()
    plt.grid(True, which="both", linestyle="--", linewidth=0.5)

    # Save the plot as a file or display it
    plt.savefig("plt_result_log/" + csv_file.replace(".csv", ".png"), dpi=300)
    # plt.show()


# Usage
if __name__ == "__main__":
    # Provide the CSV file generated by the C++ benchmark
    csv_file = "results_sorted_reverse.csv"
    plot_benchmark_results(csv_file)
